apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datamaster

resources:
  - namespace.yaml
  - mongodb-secret.yaml
  - mongodb.yaml
  - app-secrets.yaml
  - api.yaml
  - dashboard.yaml
  - portal.yaml

configMapGenerator:
  - name: mongodb-init
    files:
      - init_mongo.js=../../../scripts/init_mongo.js

generatorOptions:
  disableNameSuffixHash: true
