apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: datamaster
  labels:
    app: spark-master
spec:
  type: NodePort
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30180
    - name: rpc
      port: 7077
      targetPort: 7077
  selector:
    app: spark-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: datamaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark
          image: bitnamilegacy/spark:3.5.5
          ports:
            - containerPort: 8080
            - containerPort: 7077
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: datamaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark
          image: bitnamilegacy/spark:3.5.5
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077
            - name: SPARK_WORKER_MEMORY
              value: 2G
            - name: SPARK_WORKER_CORES
              value: "2"
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
